et lessons = [
    {
        'id': 1,
        'subject': "Math",
        'location': "Boston",
        'price': 49,
        'Numberofspaces': 5, 
        'image': "images/math.png",
    },
    {
        'id': 2,
        'subject': "English",
        'location': "New York",
        'price': 30,
        'Numberofspaces': 5, 
        'image': "images/English.jpg",
    },
    {
        'id': 3,
        'subject': "Physics",
        'location': "London",
        'price': 75,
        'Numberofspaces': 5, 
        'image': "images/Physics.png",
    },
    {
        'id': 4,
        'subject': "Chemistry",
        'location': "England",
        'price': 60,
        'Numberofspaces': 5, 
        'image': "images/Chemistry.png",
    },
    {
        'id': 5,
        'subject': "Biology",
        'location': "Russia",
        'price': 40,
        'Numberofspaces': 5, 
        'image': "images/Biology.jpg",
    },
    {
        'id': 6,
        'subject': "History",
        'location': "Colombia",
        'price': 30,
        'Numberofspaces': 5, 
        'image': "images/History.png",
    },
    {
        'id': 7,
        'subject': "Geopgraphy",
        'location': "London",
        'price': 24,
        'Numberofspaces': 5, 
        'image': "images/Geography.png",
    },
    {
        'id': 8,
        'subject': "Music",
        'location': "Mosko",
        'price': 35,
        'Numberofspaces': 5, 
        'image': "images/Music.png",
    },
    {
        'id': 9,
        'subject': "Art",
        'location': "Hawaii",
        'price': 53,
        'Numberofspaces': 5, 
        'image': "images/Art.png",
    },
    {
        'id': 10,
        'subject': "Economics",
        'location': "London",
        'price': 40,
        'Numberofspaces': 5, 
        'image': "images/Economics.jpg",
    },
]
  
